CREATE SEQUENCE BANK_PK_SEQ START WITH 1;  

CREATE TABLE BANK
(
       ID INT8 NOT NULL,
       BANK_NAME VARCHAR(40) NOT NULL,
       BANK_IDENTIFIER VARCHAR(40)  NOT NULL,
       PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX BANK_NAME_IDENTIFIER ON BANK (BANK_IDENTIFIER);